version: '3'
services:
  # starter-service:
  #   container_name: starter-service
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: 'npm run dev'
  #   restart: always
  #   env_file:
  #     - .env
  #   ports:
  #     - '3000:3000'
  #     - '9229:9229'
  #   volumes:
  #     - ./:/app
  #     - '/app/node_modules'

  starter-mongo:
    image: 'mongo:7.0'
    container_name: starter-mongo
    ports:
      - '27017:27017'
    volumes:
      - './.data/mongo:/data/db'
      - './.data/mongoconfigdb:/data/configdb'
